### PR TITLE
Improve App Icon

### PR DESCRIPTION
**Pull request by daudix**
First, thank you very much for this app, I always wanted a fast store to just install an app!

Update app icon, tried to keep the idea of "Little Store"

Inspired by current icon, [GNOME Apps](https://apps.gnome.org) banner and [ElementaryOS AppCenter](https://appcenter.elementary.io/)

# Normal

Preview

# Devel

Preview-Devel

_I will change symbolic icon soon_

### CODE REVIEW

**Comment by mijorus** [comment]
This is what I call a proper icon, thank you!

Btw I got the `computer-symbolic` icon from [this app](https://gitlab.gnome.org/World/design/icon-library), where did you get that icon?

**Comment by mijorus** [comment]
Also, I see yo have uploaded a `.Devel` icon. 
How can I use it? Could you please link some documentation? thank you

**Comment by mijorus** [comment]
Also, is it the AppCenter's icon but recolored?

**Comment by daudix** [comment]
> This is what I call a proper icon, thank you!
> 
> Btw I got the `computer-symbolic` icon from [this app](https://gitlab.gnome.org/World/design/icon-library), where did you get that icon?

There is app called "icon library", there is a lot of GNOME icons, maybe you have older version of this app?

image

**Comment by daudix** [comment]
> Also, is it the AppCenter's icon but recolored?

No, I maked this icon from scratch, but yes, it inspired by AppCenter icon a lot :)

**Comment by daudix** [comment]
> Also, I see yo have uploaded a `.Devel` icon. How can I use it? Could you please link some documentation? thank you

[Not exactly what you need](https://developer.gnome.org/documentation/tutorials/beginners/getting_started/content_view.html?highlight=devel), but only thing that I found at this moment, it used when you build app from repo, or app is uploaded to GNOME Nightly flatpak repo

**Pull request merged**
